name: Continous Integration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm ci
      - run: npm run lint

  test:
    needs: eslint
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # https://github.com/marketplace/actions/create-env-json
      - name: Set environment variables cypress.env.json
        uses: schdck/create-env-json@v1
        with:
          file-name: 'cypress.env.json'
          APP_ID: ${{ secrets.DEV_FIREBASE_PROJECT_ID }}
          API_KEY: ${{ secrets.DEV_FIREBASE_API_KEY }}
          UID_JOHN_DOE_TEST: ${{ secrets.DEV_UID_JOHN_DOE_TEST }}

      - run: cat cypress.env.json

      # https://github.com/SpicyPizza/create-envfile
      - name: Set environment variables .env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_APP_NAME: '@Trap.io'
          envkey_BASE_URL: 'http://localhost:3000'
          envkey_ENV: 'development'
          envkey_FIREBASE_API_KEY: ${{ secrets.DEV_FIREBASE_API_KEY }}
          envkey_FIREBASE_PROJECT_ID: ${{ secrets.DEV_FIREBASE_PROJECT_ID }}
          envkey_IMAGE_PROFILE: ${{ secrets.DEV_IMAGE_PROFILE }}
          envkey_USERNAME: ${{ secrets.DEV_USERNAME }}
          file_name: .env

      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
#          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          CYPRESS_TEST_UID: ${{ secrets.DEV_UID_JOHN_DOE_TEST }}
