name: Continous Integration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y chromium-browser
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm ci
      - run: npm build
      - run: npm t
